version: '3.9'

services:
  graphql-app:
    build: ./graphql-app
    volumes:
      - "./graphql-app:/app"
    ports:
      - "4000:4000"
    expose:
      - 4000
    environment:
      - port=4000
    depends_on:
      - db
    
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
