version: '3.9'

services:
  graphql-app:
    image: graphql-app:latest
    # build:
    #   context: "./graphql-app" 
    #   target: ${DOCKER_TARGET_BUILD}
    volumes:
      - "./graphql-app:/app"
    env_file:
      - .env
    ports:
      - "${GRAPHQL_APP_PORT}:${GRAPHQL_APP_PORT}"
    environment:
      - PORT=${GRAPHQL_APP_PORT}
    depends_on:
      - db
    
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
